## Use it when Google Auth configured, and update the docker-compose-letsemcrypt.yaml to use this Dockerfile
FROM mediacms/mediacms:5.0.1

# Install required packages for cryptography
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libssl-dev \
    libffi-dev \
    python3-dev \
    cargo \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
RUN pip install PyJWT cryptography
